// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DeliveryStatus.
const (
	DeliveryStatusAccepted  DeliveryStatus = "accepted"
	DeliveryStatusDelivered DeliveryStatus = "delivered"
	DeliveryStatusPickedUp  DeliveryStatus = "picked_up"
	DeliveryStatusPosted    DeliveryStatus = "posted"
)

// Defines values for DeliveryPatchStatus.
const (
	DeliveryPatchStatusAccepted  DeliveryPatchStatus = "accepted"
	DeliveryPatchStatusDelivered DeliveryPatchStatus = "delivered"
	DeliveryPatchStatusPickedUp  DeliveryPatchStatus = "picked_up"
)

// Defines values for ListDeliveriesParamsStatus.
const (
	Accepted  ListDeliveriesParamsStatus = "accepted"
	Delivered ListDeliveriesParamsStatus = "delivered"
	PickedUp  ListDeliveriesParamsStatus = "picked_up"
	Posted    ListDeliveriesParamsStatus = "posted"
)

// Delivery defines model for Delivery.
type Delivery struct {
	AssignedTo          *string        `json:"assignedTo"`
	BusinessAddress     string         `json:"businessAddress"`
	BusinessId          *string        `json:"businessId,omitempty"`
	BusinessLocation    GeoPoint       `json:"businessLocation"`
	BusinessName        string         `json:"businessName"`
	CreatedAt           *time.Time     `json:"createdAt,omitempty"`
	CreatedBy           *string        `json:"createdBy,omitempty"`
	DestinationAddress  string         `json:"destinationAddress"`
	DestinationLocation GeoPoint       `json:"destinationLocation"`
	Id                  *string        `json:"id,omitempty"`
	Item                string         `json:"item"`
	Status              DeliveryStatus `json:"status"`
}

// DeliveryStatus defines model for Delivery.Status.
type DeliveryStatus string

// DeliveryCreate defines model for DeliveryCreate.
type DeliveryCreate struct {
	BusinessAddress     string   `json:"businessAddress"`
	BusinessLocation    GeoPoint `json:"businessLocation"`
	BusinessName        string   `json:"businessName"`
	DestinationAddress  string   `json:"destinationAddress"`
	DestinationLocation GeoPoint `json:"destinationLocation"`
	Item                string   `json:"item"`
}

// DeliveryPatch defines model for DeliveryPatch.
type DeliveryPatch struct {
	AssignedTo *string              `json:"assignedTo"`
	Status     *DeliveryPatchStatus `json:"status,omitempty"`
}

// DeliveryPatchStatus defines model for DeliveryPatch.Status.
type DeliveryPatchStatus string

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// GeoPoint defines model for GeoPoint.
type GeoPoint struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListDeliveriesParams defines parameters for ListDeliveries.
type ListDeliveriesParams struct {
	Status *ListDeliveriesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Lat    *float64                    `form:"lat,omitempty" json:"lat,omitempty"`
	Lng    *float64                    `form:"lng,omitempty" json:"lng,omitempty"`

	// R Radius in kilometres from (lat,lng)
	R         *float64   `form:"r,omitempty" json:"r,omitempty"`
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// ListDeliveriesParamsStatus defines parameters for ListDeliveries.
type ListDeliveriesParamsStatus string

// CreateDeliveryJSONRequestBody defines body for CreateDelivery for application/json ContentType.
type CreateDeliveryJSONRequestBody = DeliveryCreate

// UpdateDeliveryJSONRequestBody defines body for UpdateDelivery for application/json ContentType.
type UpdateDeliveryJSONRequestBody = DeliveryPatch
